# base hyparams for training 
# ------------DDP ----------------
DIST:
  DISTRIBUTED: 1
  NGPU: 1
  RANK: -1
  DIST_BACKEND: "NCCL"
  LOCAL_RANK: -1

MODEL_NAME: "FCN_8S"
DATASET_TYPE: "VOC"
# ------------VOC DATASET ---------------
VOC_DATASET:
  TRAIN_FILE: "/data/jiangmingchao/data/code/SegmentationLight/datasets/voc2012/data/VOC/seg_train.log"
  VAL_FILE: "/data/jiangmingchao/data/code/SegmentationLight/datasets/voc2012/data/VOC/seg_val.log"
  NUM_CLASSES: 21

# ------------VOC_AUG DATASET ---------------
VOC_AUG_DATASET:
  TRAIN_FILE: "/data/jiangmingchao/data/code/SegmentationLight/datasets/voc2012/data/VOC_AUG/seg_train.log"
  VAL_FILE: "/data/jiangmingchao/data/code/SegmentationLight/datasets/voc2012/data/VOC_AUG/seg_val.log"
  NUM_CLASSES: 21

# ----------Transformes ----------------
DATA:
  CROP_SIZE: [320, 320]


# TODO
# ---------- Others DATASET--------------
# ---------- Custom DATASET -------------

# -----------SUMMARY----------------
SUMMARY:
  SAVE_PATH: "/data/jiangmingchao/data/AICutDataset/Segmentation/"
  CHECKPOINTS: "checkpoints"
  LOG: "log_dir"

# -----------OPTIMIZER--------------
OPTIMIZER:
  OPTIM_NAME: "SGD"
  LEARNING_RATE: 1e-1
  COSINE: 1
  FIX: 0
  WEIGHT_DECAY:  1e-4
  MOMENTUM: 0.9
  BATCH_SIZE: 64
  NUM_WORKERS: 32

# ------------EPOCHS------------------
WARMUP_EPOCHS: 5
MAX_EPOCHS: 90
FREQENCE: 1
  
SYNCBN: 0